### ISSUE TITLE
Přidat vzdálenostní rrEvent

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#167]
Vhodné pro kolejiště, kde se zastavuje na čas a ne na IR čidla/detektory apod. Např. kolejiště MS.
Asi by šlo o přidání dalšího typu RailroadEventu, kterému by se zadala délka od vkročení do úseku.

K diskuzi:
* Má se zadávat pouze délka, po které má spadnout rychlost na 0?
* Nebo délka, na kterou má zastavit – je třeba mít údaj o dojezdu z konkrétních rychlostí.
* Pokud se má vzít v potaz i to, že se HV rozjíždí, musí být uložena globální charakteristika HV.

**Comment by petrilakm** [comment]
Zda zadávat délku do místa kde zastavit nebo zhodit rychlost na 0 by mohlo být volitelné. Začal bych místem, kde zhodit rychlost, bude to jednodušší na implementaci. Další kolejiště kde to bude použito je HR (Honza Ryvola).

**Comment by horacekj** [comment]
Souhlasím. Obecně je po této funkcionalitě poměrně velká poptávka od vícero lidí používajících hJOP.
