### ISSUE TITLE
Doplnit dokumentaci: běží je hodnota 0 nebo 1

### ISSUE THREAD

**Issue by kudlav** [kmzbrnoI/hJOPserver#175]
Doplnit dokumentaci: běží je hodnota 0 nebo 1

```
Server → klient
-;MOD-CAS;běží;násobič;čas;/používán/

    používán je hodnota 0 nebo 1. V případě nevyplnění se interpretuje jako 1.
```

https://github.com/kmzbrnoI/hJOPserver/wiki/panelServer-mc#klient--server

**Comment by horacekj** [comment]
Nechceš to doplnit sám?

**Comment by horacekj** [comment]
Hotovo.

**Comment by horacekj** [comment]
(Tato zpráva se generovala úplně úchylně, nový hJOPserver bude vždy posílat vše)

**Comment by kudlav** [comment]
Doplněno ještě víc. Teď jsou pod čarou specifikovány všechny položky. Volitelnost ve specifikaci stejně zůstane (zpětná kompatibilita).
