### ISSUE TITLE
Zvážit neumožnění postavení PC proti zastavujícímu vlaku na staniční koleji

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#184]
Když vlak zastavuje, úsek už nemá závěr, takže je možné proti němu postavit protisměrnou JC. Může být tvrdá bariéra bránící postavení.

**Comment by OndraHoust** [comment]
U ETB je tam minutový časák, který znemožňuje postavic PC. Tzv. Protisměrné výluky (relé XC). Čas se spouští obsazením staniční koleje.  Končí doběhnutím času nebo uvolněním koleje.

![IMG_20220608_205627](https://user-images.githubusercontent.com/55841765/172701059-e1190c3f-b4ef-4a82-b105-97f8843c856b.jpg)

![XC](https://user-images.githubusercontent.com/55841765/172703098-223a5065-38c3-45b9-b53f-ddb31c810caf.png)

**Comment by horacekj** [comment]
Lze simulovat nově implementovaným podržením závěru na staniční koleji. Viz #240
