### ISSUE TITLE
INI soubory používají středník uprostřed hodnot

### ISSUE THREAD

**Issue by kudlav** [kmzbrnoI/hJOPserver#185]
INI soubory `users.ini`, `mJC.ini` používají k oddělení více hodnot středník `;`.

Středník je vyhrazen pro komentáře, parsování jiným programem než hJOP způsobí, že hodnota je zpracována jen po první výskyt středníku na řádku. https://en.wikipedia.org/wiki/INI_file#Comments_2

Např:
`ORs=(Br;2)(BrD;2)(De;2)(Ho;2)(Hr;2)(Iv;2)(Le;2)(Me;2)(Na;2)(Os;2)(Po;2)(Sk;2)(Sy;2)`
se zpracuje jako:
`ORs=(Br`

**Comment by horacekj** [comment]
Ono těch souborů asi bude víc, myslím minimálně ještě `.spnl`, `.opnl`.
Středníky nejsou ideální, změníme na jiné znaky.
