### ISSUE TITLE
Přidat zpoždění uvolnění KO

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#188]
Je poptávka o tom, aby hJOP uměla spolupracovat i s jednoduššími dekodéry, které neumožňují zpoždění uvolnění.

**Comment by OndraHoust** [comment]
Jo takhle. Osobně jsem se s tím ještě nesetkal. V tom případě by to asi nebylo na škodu.

**Comment by horacekj** [comment]
To bychom mohli zpoždění implementovat úplně všude - ve všch blocích. To je nesmysl. Neřešit v hJOPserveru, ale v RCS knihovně.
