### ISSUE TITLE
Zrychlit při vjezdu do trati už při opuštění zhlaví?

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#191]
Nečekat na opuštění záhlaví.

**Comment by OndraHoust** [comment]
Vlak jede podle návěstidla. Tzn. když jede na Volno, jede/rozjíždí se maximální rychlostí bez ohledu na zhlaví nebo záhlaví.
Když má 40 a volno, jede/rozjíždí se 40 dokud neuvolní limitující výhybku. Takže ve zhášáku (záhlaví) může jet/rozjet se klidně maximální rychlostí pokud uvolní limitující výhybku. 
Výstraha max 120 dokud nechytne kód zelené. (ale to nemá cenu řešit, vzhledem k absenci vyšší rychlosti než je 120)
