### ISSUE TITLE
Zvýraznit v reliéfu nouzově zastavený vlak

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#194]
Párkrát se stalo, že obsluha nevěděla, proč vlak nejede. Neuvědomila si, že vlak nouzově zastavila. Bylo by dobré nějak zvýraznit nouzově zastavený vlak. V trati +- jde poznat (červená barva), na staniční koleji ne. Asi nějaké podbarvení/rámeček okolo čísla vlaku.

**Comment by OndraHoust** [comment]
Jen bych tomu shodil návěstidlo s výpisem Porucha povolující návěsti. To ti pak dojde...

**Comment by horacekj** [comment]
Implementováno. Číslo nouzově zastaveného vlaku bliká (na staniční koleji i u úvazky v trati). Nouzové zastavení aktivuje výpravčí v menu vlaku, podobně jako *adresní STOP* na nových ESA s RBC.
