### ISSUE TITLE
Konfigurovatelný počet zároveň stavěných výhybek v JC

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#211]
Umožnit konfigurovatelný počet zároveň stavěných výhybek v JC. Pro každou JC vlastní číslo (stačílo by pro jednu stanici - zdroj).

**Comment by petrilakm** [comment]
Určitě ne pro každou JC. Bude se to dělat kvůli zatížení zdroje (pak dává smysl na celou stanici/kolejiště) a nebo pro simulaci nějakého zab. zař. (tam dává smysl pro celou stanici)

**Comment by OndraHoust** [comment]
V reálu záleží na konfiguraci napájení přestavníků. Zkrátka kolik napájecích traf tam je, obvyklé je jedno trafo na zhlaví. Ale všeobecně se dá říct, že víc jak 6 přestavníků se zároveň netočí. (jsou samozřejmě vyjímky)

**Comment by horacekj** [comment]
Konfigurovatelnost pro každou jízdní cestu umožní libovolné kombinace, je univerzální. Nevidím důvod, proč ji nepoužít.

**Comment by petrilakm** [comment]
Bude dost nepraktické to editovat.

Dne čt 29. čvn 2023 9:59 uživatel Jan Horáček ***@***.***>
napsal:

**Comment by horacekj** [comment]
Implementován globální počet, lokální počet pro kařdou JC zatím nebudu dělat. Pokud by vznikl požadavek na nastavení počtu pro každou cestu / stanici / whatever, můžeme tento bug znovu otevřít.
