### ISSUE TITLE
Přejezd: umožnit vypnout pozitivu za specifických situací

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#212]
U přejezdu řízeného z hJOP umožnit vypnout pozitivu, pokud je v blízkosti přejezdu vlak. Nejde pouze o reakci na obsazenost blízkých KO, protože přejezd může být krytý odvratem či výkolejkou.

**Comment by horacekj** [comment]
Umožnit vypnout na základě KO, poloh výhybek či na základě obsazení KO při konkrétní poloze výhybek.

**Comment by OndraHoust** [comment]
Pokud je přejezd ve stanici (nebo v obvodu stanice) a je přes něj postavená vlaková cesta, pozitivka se automaticky vypíná. Posunová cesta zavírá přejezd vždy.

**Comment by OndraHoust** [comment]
Dneska jsem zjistil, že opravdu i poloha výhybky vypíná pozitivku. V žst Hustopeče u Brna výhybka 3 vypíná pozitivku na staničním přejezdu H když má polohu mínus (na manipulační kolej 2) i když je hlídaná počítači náprav... Nevim jak by to bylo, kdyby byla kolej volná.
![IMG_20230905_095156](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/77171b0d-eb75-47f1-8d47-1ea8a105d264)

**Comment by horacekj** [comment]
Návrh zadávání: jednotlivé podmínky se zadávají řádek po řádku, na každém řádku jedna.

Příklad řádku: `62:+,32:- > 130,131:1`. Význam: pokud je výhybka ID 62 v poloze + a výhybka id 32 v -, pozitiva má svítit právě tehdy, pokud je úsek 130 volný a 1. část úseku 131 volná.

Zpracovávají se vždy všechny řádky, pokud se více matchne, použijí se úseky ve všech matchnutých řádcích. Pokud je nějaká výhybka v nepoloze, matchne se podmínka na + i na - (nepoloha = potřeba kontrolovat volnost více kolejí).

Speciální případy:
* před symbolem `>` nic není: použije se vždy
* za symbolem `>` nic není: neplatná volba
* za symbolem `>` je pouze znak `F`: bere se jako trvale obsazený KO, pozitiva nesvítí
* za symbolem `>` je pouze znak `T`: bere se jako trvale uvolněný KO, pozitiva svítí

Příklad definice pro přejezd H v Ondrově reliéfu žst. Hustopeče u Brna:

```
> SK, 1bK, V2-3, T1, 1aK, 3K
Vk2:- > 2k
```

1bK je úsek mezi Se5 a Se4.

Vycházím z předpokladu, že návěstidlo na pozitivu nikdy nemá vliv - například vjezdové návěstidlo S. Vliv má pouze přímá boční ochrana - výkolejka nebo odvrat. Proto jsou uvedeny 1aK, 3K a T1 nezávisle na poloze výhybek. Je to správný předpoklad?

**Comment by horacekj** [comment]
Zkusil jsem si vytvořit nějaký obecný ukázkový případ.

![example](https://github.com/kmzbrnoI/hJOPserver/assets/12673442/0387a266-34e2-4c53-916a-8c0cf35effac)

Definici pozitivy pro přejezd A bych si představoval takto:

```
> T1, 1bK, 1aK, V1-5, 3K, 1K
Vk2:- > F
6:- > F
4a:- > 2K
4a:-, Vk3:- > 4K
```

**Comment by OndraHoust** [comment]
> Vycházím z předpokladu, že návěstidlo na pozitivu nikdy nemá vliv - například vjezdové návěstidlo S. Vliv má pouze přímá boční ochrana - výkolejka nebo odvrat. Proto jsou uvedeny 1aK, 3K a T1 nezávisle na poloze výhybek. Je to správný předpoklad?

No, zrovna návěstidlo na to má vliv víceméně největší. 
Zítra zkusím ofotit tabulku přejezdu H v Hustopečích, kde jsou uvedené podmínky pro rozsvícení pozitivy. (snad, máme čtvrtletní tak nevim jestli bude čas... 🥲 )
K tvému příkladu:
Jakákoliv VC pozitiva zhasne ikdyž je obvod volný. (viz. obrázek Vranovic dole) Jsou samozřejmě vyjímky a další podmínky v závislosti na typu PZZ a SZZ a vzájemných vazbách. Jinak se chová ETB s releovou vazbou na přejezd (a především fyzickýmy závěry úseků) a ESA.
Jakákoliv PC přes přejezd zavírá přejezd. 
Obsazení tratě bez postavené VC nemá vliv na pozitivu
Poloha V1,V2, V3 a V4a/Vk3 nemá vliv na pozitivu, V6/5- zhasíná pozitivu, V4b- zhasíná pozitivu, Vk2- zhasíná pozitivu
Obsazení SK1b zhasíná pozitivu
Obsazení jakékoliv koleje vyjma SK1b BY NEMĚLO mít vliv na pozitivu
Obsazení SK1a zavírá přejezd
Obsazení všech vyhybek vyjma V6 a V4 zavírá přejezd bez ohledu na postavenou nebo nepostavenou cestu a poloze vyhybek (oficiálně: obvod ujetí vozidel)

Další příklad z žst. Vranovice: (snad umíš značky schémat a logiku zab. zař.)
![VRA](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/315d2127-38e1-46cf-b73e-bfffcfb72452)
![ASP](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/464c29ea-9ee5-4bcf-8156-5a73e6e8d4f8)
![AUV](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/b7771f0b-8688-4327-a7ad-666854a4e97e)



Celá tahle problematika je popsaná v normě ČSN 34 26 50 jenže je složitá jak parní mlátička... Zítra se mi dostane do ruk, tak to zkusím trochu pročíst a kdyžtak upřesním/opravím co jsem zde napsal.

**Comment by OndraHoust** [comment]
Jinak ještě pro doplnění jak to asi vypadá (L=0 znamená že není postavená cesta)
![H](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/d9058bbd-203e-4d7a-baf4-3502818be118)
přejezd v Hustopečích

![vra](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/fbc6cec6-37ad-4448-80fb-da453a5c04cd)
přejezd ve Vranovicích

**Comment by horacekj** [comment]
Díky. Kouknul jsem se na schémata a ještě jsem se podíval do normy. Pozitiva opravdu má zhasínat, pokud je přes přejezd postavená cesta, byť je vlak někde hodně daleko.

V implementaci je potřeba nějak vyjmenovat seznam dotčených návěstidel – nestačí cesty, protože pozitiva musí reagovat i na rozsvícení PN bez podpory zabezpečovacího zařízení. Nejsem si však jistý, jestli stačí pouze vyjmenovat seznam návěstidel, jejichž nestůj zhasíná pozitivu. Například rozsvícení návěsti "Posun dovolen" na Se7 v mém příkladu podle mě nemusí nutně zhasnout pozitivu, protože posunová cesta může být postavena na 2aK. Existuje reálně situace, ve které je "Předepsaná poloha návěstidel" navázána například na polohu odvratu?

Je to složitý jak mlátička...

**Comment by horacekj** [comment]
V4a- by podle mě nemusela rovnou zhasínat pozitivu, pokud jsou volné kolejové obvody 2K, 4K, V4a-4b.

Souhlasím, že při PC Se7->1bK jde přejezd A rovnou do výstrahy nezávisle na obsazení úseků, pozitiva se tedy automaticky zhasíná výstrahou.

Navrhuji zachovat původní navrhovaný formát, přičemž se v pravé části za `>` může objevit i návěstidlo. Toto návěstidlo musí být na stůj pro rozsvícení pozitivy.

Konkrétně pro můj příklad výše:
```
> T1, 1bK, 1aK, V1-5, 3K, 1K, L, S1, S3
Vk2:- > F
6:- > F
4a:- > 2K, S2
4a:-, Vk3:- > 4K, Se7
```

Tento zápis například definuje, že rozsvícení povolující návěsti na S2 zhasíná pozitivu jen tehdy, pokud je 4a-. Takže PC S2>2aK pozitivu nezhasne, naopak VC S2->T1 pozitivu zhasne, byť je 2K volná.

**Comment by petrilakm** [comment]
Stále nechápu k čemu je F v právo.
Kdyz v levo se dá začít šipkou bez písmena.
Já bych F zrušil a nedával za šipku už nic.

Dne út 24. říj 2023 9:23 uživatel Jan Horáček ***@***.***>
napsal:

**Comment by OndraHoust** [comment]
Vidím, že jsem si trochu zaměnil V4a s V4b 🥲 (opraveno)... 

No a nebylo by fakt jednoduší a hlavně přehlednější vypisovat cesty, polohy vyhybek a volné úseky? Návěstidla bych tam vůbec nevypisoval, není to za mě potřeba, protože jediný případ kdy to nebude podchycené je PN a to je samo o sobě riziková fuknce u které máš za povinnost zavřít přejezdy. 

Udělat tři okýnka pro obvody, vyhybky a VC, kde by sis jen vybral ID nebo adresu rsc a hodnotu pro ROZSVÍCENÍ pozitivy? 
Např. pro obvody ID25:0 nebo 65:0 (ID25:volný (1bK)) (a teoreticky bys ani nemusel vybírat volný nebo obsazený-vždy musí být volný žejo...) 
pro vyhybky zase ID5:+, ID4+, ID12+ (V5+, V4a+, Vk2+) nebo tak jako při vytváření cesty.
a pak vyjmenovat jednotlivé VC.

Pro VÝSTRAHU by stačilo jen jedno okýnko pro obvody, protože zavření bude už bude v definici jednotlivých cest
obvody: ID25:1, ID27:1 (1aK a V1-5 obsazené) + přibližováky, vzdalováky atd...

Nic víc
Všechny okna bych udělal stylem rozevírací roletky jako třeba u Pst... Prostě vybereš co chceš. Takhle něco vypisovat mi nepřijde nijak přehledný

**Comment by OndraHoust** [comment]
Jakože něco na tenhle způsob:
![pzz](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/c0a19c8d-1e86-4c36-b3b8-93856fcb4a34)

**Comment by petrilakm** [comment]
Jenže ten okny kovy systém je dost na houby. Protože tam není jak pořádně zadat při kterých polohách jde o jaké úseky.
Ten textový zápis je sice méně přehledný, ale umí mnohem víc věcí.

Ono by bylo ideální, kdyby tam byl nějaký grafický okýnko vy editor, který by generovala ten textový zápis.
Ale jen rozbalovací i nabídkami se spousta věcí nedá udělat.

**Comment by OndraHoust** [comment]
Sice toho asi umí víc, ale nadruhou stranu proč vytvářet tak složitý podmínky... Proč to nedělat jednoduše... není boční ochrana->zhasni pozitivku. Hotovo. Proč tam dávat ještě zbytečný podmínky... není boční ochrana, ale je volný úsek... proč... A navíc zrovna v tomhle případě by přece šlo udělat ve sloupci Výhybky ještě jednu záložku vedle polohy vyhybek, kde by byla třeba ta podmínka. Byly by tam vlastně dvě podmínky v „sérii”. Takže reálně tam bude třeba:
V1+
V2+
V3+ 
V3- | 3K 

Nikde jsem to neviděl. Za mě zbytečný.

**Comment by horacekj** [comment]
Díky za náměty. Myslím, že `F` vpravo je opravdu k ničemu a že by bylo dobré mít nějaké GUI na editaci - minimálně místo ID bloků umožnit zadávat jména bloků. Zkusím to ještě promyslet.

Z příkladů je vidět, že není možné navázat pozitivu pouze na návěsti. Někdy návěsti musí být zapodmínkovány polohou výhybek (viz S2 v mém příkladu). Myslím, že obdobně je to s obsazením úseků, ačkoliv pro toto tvrzení nemám podklad z praxe, pouze mi zní intuitivně a v souladu s normou. Zkusím se poptat ještě dalších lidí, kteří se točí okolo přejezdů.

**Comment by petrilakm** [comment]
Tak ID bloku by chtělo nahradit všude za název bloku. Nechápu, kde tam vidíš problém, když žádný není. Když si ten, co editujes bloky vytvoří 2 bloky se stejným jménem, tak je to jeho problém. hJOP to nemusí nijak systémové řešit. Není třeba chránit uživatele před ním samotným!

**Comment by petrilakm** [comment]
> Sice toho asi umí víc, ale nadruhou stranu proč vytvářet tak složitý podmínky... Proč to nedělat jednoduše... není boční ochrana->zhasni pozitivku. Hotovo. Proč tam dávat ještě zbytečný podmínky... není boční ochrana, ale je volný úsek... proč... A navíc zrovna v tomhle případě by přece šlo udělat ve sloupci Výhybky ještě jednu záložku vedle polohy vyhybek, kde by byla třeba ta podmínka. Byly by tam vlastně dvě podmínky v „sérii”. Takže reálně tam bude třeba:
> V1+
> V2+
> V3+ 
> V3- | 3K 
> 
> Nikde jsem to neviděl. Za mě zbytečný. 

Ale teď si opravdu protiřečíš sám.
Nejprve jsi tu posílal tabulky od SŽ a teď se snažíš tvrdit, že je to potřeba mít co nejjednodušší. Přitom samotná Správa železnic v tom má chaos, protože ty pravidla co 10 let mění, ale na stávajících zařízeních je nechává jak jsou v době spuštění.

Předně je třeba si uvědomit, jaké jsou cíle hJOP a jaká je cílová skupina. Zda je to pro vlačkaře, tedy stačí že vlak jezdí. A nebo je to pro modeláře, kteří očekávají nějaké realistické chování. Já se kloním k druhé skupině.

Pokud je potřeba jednoduchá editace kolejiště a jednoduché ježdění, tak je jasná volba RailCo. hJOP nemusí umět to samé co nabízí již existující software.

**Comment by OndraHoust** [comment]
> Z příkladů je vidět, že není možné navázat pozitivu pouze na návěsti. Někdy návěsti musí být zapodmínkovány polohou výhybek (viz S2 v mém příkladu).

Právě že v tomhle konkrétním případě tě absolutně nezajímá co na návěstidle svítí, protože dokud bude V4a+ (tedy na kolej 2aK) tak pozitiva svítí a je jedno jestli je PC Se7->2aK nebo PC S2->2aK nebo i Se4->2K a Se4->6K. Ve všech případech je splněná boční ochrana přejezdu, tedy V4a+.  Defacto žádná JC od S2 nemusí být nijak zatesaná do přejezdu, protože jakákoliv jiná JC bude mít V4a-, takže zhasíná pozitivka v případě VC a nebo se zavírá přejezd v případě PC.

**Comment by horacekj** [comment]
V mém příkladu ale přece nemusí pozitiva zhasínat vždy při V4a-. Mně jde o vymyšlení takového návrhu, který pokryje co nejvíc prakticky možných situací. Nepřímá boční ochrana tvořená návěstidlem S2 může být stejně dobrou ochranou jako přímá boční ochrana pro rozsvícení pozitivy. Pokud bychom chtěli navázat pozitivu na návěst S2, musíme toto navázání zapodmínkovat polohou výhybky 4a.

**Comment by OndraHoust** [comment]
> Ale teď si opravdu protiřečíš sám.

To že SŽ má nesmyslný podmínky, který ani nemůžou nastat a tím si protiřečí není můj problém. Já je nevymyslel. Ale pravdou je, že co platí třeba ve zmíněných Vranovicích (jakákoliv postavená cesta zhasíná pozitivku) neplatí v Hustopečích... Proto jsem hned zezačátku psal, že záleží i na vazbě a typu SZZ a PZZ. (ve Vranovicích ETB a EA r.v.2000 a Hustopeče ESA a PZZJ r.v.2020) I proto jsem psal, že bych to zas tak nehrotil, protože vím, že v reálu je prostě všechno jinak a spousta věcí si zkrátka odporuje. (viz. obě schémata z Vranovic, jedno říká zhasni pozitivku a druhé říká zavři přejezd) Třeba PZZJ když jsou ve výluce tak taky svítí pozitiva (než se přiblíží vlak), dokonce i u některých nouzových stavech svítí pozitiva... Zkrátka věci, které byly dřív samozřejmé jsou dnes jinak.

**Comment by OndraHoust** [comment]
> V mém příkladu ale přece nemusí pozitiva zhasínat vždy při V4a-. 

To je pravda. 👍🏻 
Pokud bys to chtěl echt dokonale, tak bys tam měl jednu dvojpodmínku: V4a- a zárověň V4b+, protože boční ochranu by v tom případě přebrala Vk3. Takže i bez postavené cesty by svítila pozitiva.

**Comment by horacekj** [comment]
Do TextBoxu se budou zadávat názvy. Při kliku pravým volby:
* Nápověda (zobrazí MessageBox)
* Zobrazit id (zobrazí MesssageBox s názvy přeloženámi na id, jinak formát stejný)

Stejně udělat i u pokročilých voleb vlakových cest.
