### ISSUE TITLE
Lze postavit současně vlakovou a posunovou cestu přes stejné bloky.

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/hJOPserver#214]
Lze postavit současně vlakovou a posunovou cestu přes stejné bloky. Můžu dodat data pro server a panel a popis jak to jde.

Problém nastane pokud je v zásobníku vlaková a za ní hned posunová cesta. hJOP se chovám jak kdyby kontrolovala podmínky pro obě cesty současně.

levá polovina stanice. 

   S     Se1
--|>---->-----\-----<|----1k----
                       \----<|----3k----

Všechny úseky jsou volné.
zvolím VZ a postavím 3 cesty:
1. vlaková od S na 1k
2. vlaková od S na 1k (stejná jako předchozí)
3. posunová os Se1 na 1k
A pak na návěstidle S dám volbu "RC"

první cesta se v pořádku zruší.
Ale ihned se postaví cesty 2 a 3 současně:
1. návěstidlo S má volnoznak
2. úsek za S ná vlakový závěr
3. návěstidlo Se1 dovoluje posun
4. vyhýbkový úsek má posunový závěr
5. první kolej má posunový závěr

**Comment by horacekj** [comment]
Pokoušel jsem se problém reprodukovat a nepodařilo se mi to. Cesty se mi vždy stavěly korektně. Prosím o zaslání konfigurace serveru a panelu/ů.

**Comment by petrilakm** [comment]
Chybu je možné vyvolat jen se simulační RCS knihovnou. Navíc výhybky musí mít výstupy na portech >15. S reálným RCS nebo s opravenou simulační knihovnou se chyba nedá vyvolat.
