### ISSUE TITLE
Vylepšit blok přejezdu - nevyžadovat vstupy

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/hJOPserver#216]
Současný blok přejezdu podporuje HW modul anebo simulali přejezdu v hJOP.
Jenže při simulaci chce blok zadat vstupy, které ne vždy dávají smysl.
Není však způsob, jak říct, aby se daný vstup nepoužíval.
U výstupů jento již vyřešené.

Pro úspěšné použití bloku by mělo stačit zadat výstup "uzavřít přejezd" a žádné vstupy. Ty můžou ale také nemusí být.

**Comment by horacekj** [comment]
Současný blok přejezdu podporuje komunikaci s externím přejezdovým zabezpečovacím zařízením. Jednou z možností konfigurace je řízení zavírání přejezdu a blokování pozitivy přímo z hJOP.

Některé funkce však stále řeší pouze hardware PZZ. Jde především o počítání předzváněcí doby.

Ty chceš, aby se více z logiky PZZ přesunulo do hJOP a aby v kolejišti mohly být jen "hloupé" výstražníky a reproduktor? V takovém případě by bylo potřeba počítat předzváněcí dobu v hJOP.

**Comment by petrilakm** [comment]
Ano. V kolejišti pak bude jen blikače (bez reproduktorů). Nebo jen závory v případě mechanického přejezdu. Nebude zapojen žádný vstup.

Předzváněcí doba se bude muset měřit v hJOP.

**Comment by horacekj** [comment]
Implementováno, k otestování.

**Comment by petrilakm** [comment]
Otestováno. Funguje dost dobře.

Pouze pokud jsou zadané vstupy na detekci polohy závor a po spuštění nění závora ani v jedné poloze, hJOP má přejezd ve stavu "none". Přitom by měl být normálně ve výstraze. Jako by se otevíral, ale ještě nepříšla kontrola horní polohy.

**Comment by horacekj** [comment]
* [ ] Odpadnutí dolní polohy závor nemá shodit návěstidlo. TODO dořešit detaily: podmínka rozsvícení volnoznaku atd.

**Comment by horacekj** [comment]
Otestováno s moduly přejezdu na modulovce TT, považuji za funkční. Uff, to byla ale práce.
