### ISSUE TITLE
Zbavit se závislosti na jclPEImage

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/hJOPserver#217]
V souboru **helpers\version.pas** je závislost na knihovně jclPEImage.

Mám vyzkoušeno, že se dá nahradit pomocí build-in funkce **PImageNtHeaders** a **PImageDosHeader**. Je však potřeba datum a čas správně naformátovat pomocí knihovny DateUtils:
```pascal
interface

uses Windows, SysUtils, Forms, DateUtils;
```

Funkce LastBuildDate a LastBuildTime se nahradí 3-mi funkcemi:
```pascal
function LinkerTimestamp: TDateTime; overload;
begin
  Result := TTimeZone.Local.ToLocalTime(PImageNtHeaders(HInstance + Cardinal(PImageDosHeader(HInstance)^._lfanew))^.FileHeader.TimeDateStamp / SecsPerDay + UnixDateDelta);
end;

function LastBuildDate(): string;
begin
  DateTimeToString(Result, 'dd. mm. yyyy', LinkerTimestamp);
end;

function LastBuildTime(): string;
begin
  DateTimeToString(Result, 'hh:mm:ss', LinkerTimestamp);
end;
```

**Comment by horacekj** [comment]
hJOPserver využívá mimo `jclPEImage` také balíček `JclDebug`, který používá k vypsání tracebacku výjimky do logů (včetně čísel řádků kódu a jmen funkcí). Tuto funkci chci v hJOP zachovat. Jelikož se odstraněním závislosti na `jclPEImage` nezbavím závislosti na *JEDI Code Library*, nevidím ve změně zjišťování verze až takovou přidanou hodnotu.

Popsaná úprava mi dává smysl v programech, které využívají z JEDI Code Library pouze `jclPEImage`, například `mtb-simulator-lib`. Co myslíš?

**Comment by petrilakm** [comment]
Odstranil bych to i tady. Když si chci zkompilovat hJOP server v community
edition, tak méně závislosti je výhoda.

Odstranil bych to všude, kde to jde.

Když se v budoucnu nějak vyřeší logování výjimek, tak nebude jcl potřeba
vůbec. Knihovna je asi dobrá, ale má naprosto neschopný instalátor.

Dne čt 29. čvn 2023 9:53 uživatel Jan Horáček ***@***.***>
napsal:
