### ISSUE TITLE
Zámek po výpadku polohy zamčených výhybek se sám odemkne.

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/hJOPserver#223]
V případě, že se restartuje MTB deska, která hlásí koncové polohy zamčených výhybek, tak se zámek zobrazí inverzně modrou barvou - nesoulad polohy výhybek.
Když se indikace koncových poloh obnoví, zámek zůstane ve stavu nesouladu. Měl by se vrátit do normálního stavu (klíč zapevněn a výhybky mají správnou polohu). Zamek si má pamatovat, že je klíč zapevněn. Teď se musí ručně dát ZUZ, tedy to vypadá, že klíč je uvolněný.

**Comment by horacekj** [comment]
Proč by se měl vrátit do stavu *klíč zapevněn*? Mně současné chování celkem dává smysl: výpravčí zámek uzamkne, až si je jistý, že vše v kolejišti je v pořádku. Bohužel se tady asi nemůžeme opřít o žádné skutečné chování např. stavědla ESA, protože tato situace nastává pouze v modelu. Nebo máme nějakou oporu?

**Comment by petrilakm** [comment]
Naopak se opírá o skutečnost. Klíč že za nu nikdy sám nevypadne a nemá se co uvolňovat, když k tomu nedá vypravčí pokyn. Když je nesoulad polohy (zámek zamčen, ale výhybka třeba nemá polohu) tak je zámek vybarven inverze modře. Ale klíč je stále zapevnen. Když se kontrola prestavniku obnoví, tak se symbol sám vrátí do základního stavu. Klíč je stále zapevnen a prestavník má správnou polohu.

Opírá se o to, že ve skutečnosti musí klíč uvolnit vždy vypravčí. Nikdy ne jinak.

**Comment by horacekj** [comment]
Nedokážu si vybavit stavědlo, kde by výhybka pod zámkem měla i detekci polohy. Taková situace existuje?

**Comment by petrilakm** [comment]
U zámku neexistuje, ale pomocné stavělo dohled poloh mít může. Vycházím z něj. 
Každopádně inverzní modrý symbol (nesoulad poloh) nodemkne klíč a už vůbec se neruší volbou ZUZ, tak jak tě to teď.
Upřímně pro provoz na kolejišti, bych nesoulad poloh řešil tím inverzní zámkem a volbami NS+ a NS ať to jde co nejrychleji srovnat.

**Comment by horacekj** [comment]
Asi by bylo dobré sehnat nějakou dokumentaci k chování zámků v ESA, abychom podle toho mohli implementovat chování v hJOP. Například by mě zajímalo, kdy se indikuje nesoulad poloh, kdy se tato indikace vypíná, jestli se nějak potvrzuje atd.

**Comment by petrilakm** [comment]
Ono je hlavně hloupé, že po krátkém výpadku MTB, co kontroluje dohled vyhybek se klíč sám nodemkne. Podle mě by se vše mělo samo vracet do základního (bezpečného) stavu. To že MTB vypadlo nevadí, když pak už jede.

**Comment by OndraHoust** [comment]
> 

Vybavuju si třeba Moravské Bránice nebo Moravský Krumlov... Vyhýbky zamčené na zámky s přestavníkem bez motoru. Tedy jen kontrola polohy. Myslim se to oficiálně označuje jako elektrický závorník. Docela se to rošířilo. A zrovna v Bránicích s tím býval problém, žes mohl „hodit kulu” a ztratil se dohled byť se vyhybka nepřestavila kvůli zámkům... Ale jak se zbarvil zámek už si nevzpomínám. Ale nemyslím si, že je bezpečný stav, aby se po znovuzískání dohledu nemuselo nic nouzově rušit a dělat, jakože se vlastně nic nestalo. Protože všechny podmínky musí být splněny: tzn. Klíč zasunutý, zámek zamčený a dohled +. Jakmile se jedna poruší (bez toho aniž by byl vydaný povel), je to nebezpečný stav a na 99% se to bude nouzově rušit. Ale už si to fakt nepamatuju a ruku do ohně bych za to nedal 🥲  A nasimulovat se mi to nepodařilo. Je to 12 let stará simulace... (nevim jestli už tam v té době byly) Navíc zrovna v případech výše zmíněných stanic, se muselo prvně předat Pst a až v něm předat obsluhu zámku pokud se nepletu. Výpravčí nemá možnost ani předat klíč, ale říkám, nevim jestli tam ty dohledy vyhybek už fyzicky byly v době vzniku téhle simulace.


Třeba V5 to tak měla...
![EZ](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/bd4ca8a4-87f9-405b-a502-4df2b95f9514)

Po nasimulování vyjmutí klíče z EZ, bez výpisu... (možnost simulace ztráty kontroly na V5 chybí)
![ez2](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/6f88bf65-7e0d-4ec0-b0c5-437a3865dfcf)

**Comment by horacekj** [comment]
Vyzkoušeno na reálné ESA s uzávorovanou výhybkou pod zámkem. Při odpadnutí koncové polohy symbol výhybky indikuje nepolohu a zámek se podbarví inverzně modře. Při obnovení koncové polohy se vše vrátí samo do původního stavu (zámek šedý, symbol výhybky zobrazuje koncovou polohu).

Upravit inplementaci v hJOP tak, aby se po vrácení koncové polohy automaticky obnovil stav zámku do *zamčeno*.
