### ISSUE TITLE
Umožnit zadání přejezdu bez otevíracího useku.

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/hJOPserver#224]
Je občas vhodné, aby byl přejezd držen vlakovou cestou celou dobu co cesta existuje. Teď každé zadání přejezdu v cestách vyžaduje specifikovat otevírací blok. Jde to obejít zadáním posledního bloku v cestě, ale není to intuitivní.
Když teď blok nezadám (280, , 222), tak se přejezd vůbec neuzavře.

**Comment by horacekj** [comment]
(280, , 222) je nyní neplatné zadání. Mně zadání posledního bloku v cestě připadá jako dobrý funkční přístup nevyžadující žádné speciality.

**Comment by petrilakm** [comment]
Bohužel to ale není nikde napsáno, že vybránim posledního úseku se dosáhnedané funkcionality. Musí ten otevárací úsek být zadán? On v některých případech prostě nedává smysl.

**Comment by horacekj** [comment]
Teď je hJOP implementována tak, že zadán být musí. Osobně nevidím problém v tom zadat jako otevírací úsek přejezdu prostě poslední úsek cesty.

**Comment by petrilakm** [comment]
Kdyby k hJOP existoval návod, kde by to bylo napsáno, tak bych neměl problém. Ale teď není vůbec jasně, co se má jako otevírací úsek zadat. Když ho prostě nechci zadávat. Ten otevírací úsek je totiž není navíc. Normální je držet přejezd cestou po celou dobu.

**Comment by horacekj** [comment]
Souhlasím, že editace přejezdů v jízdních cestách není úplně user-friendly. Pro mě je otevírací úsek standardní záležitost a naopak držení přejezdu po celou dobu jízdní cesty vnímám nestandardně.

**Comment by horacekj** [comment]
Další problém je, co je to "celou dobu co cesta existuje". Musí se vyřešit následující situace:
* zrušení cesty nouzovým uvolněním závěrů pouze některých úseků (úsek na kterém je / není přejezd);
* kdy otevřít přejezd při chybě během stavění jízdní cesty?

Mně přijde docela dobré, že nyní je závěr přejezdu navázán na závěr úseku, protože ten seš schopen v nejhorším nouzově zrušit. Učitě se tak nestane, že by přejezd zůstal uzavřený.

Pokud by například nezadání otevíracího úseku znamenalo implicitní nastavení otevíracího úseku na poslední úsek jízdní cesty, došlo by při nouzovém uvolnění závěru posledního úseku k otevření přejezdu, byť například úsek, na kterém přejezd fyzicky je, závěr stále má. Podle mě je to trochu neintuitivní, ale asi možné.
