### ISSUE TITLE
Zvážit číslování podúseků

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/hJOPserver#226]
V editaci zastavování na koleji/traťovém úseku se jednotlivé detektory číslují 1-4. Když se ale někde píše zápis s dvojtečkou (221:0), tak je číslování 0-3. Není to přehledné pro editaci. Použitelné ano.

**Comment by horacekj** [comment]
Jsem pro, aby se číslovalo všude stejně. Doporučil bys od 0 nebo od 1?

**Comment by petrilakm** [comment]
Pro obsluhu/editora je určitě přehlednější 1-4.

**Comment by horacekj** [comment]
Zkoušel jsem si řešení tohoto issue implementovat a asi se kloním spíše k tomu označovat části úseku 0-3. Hlavně proto, že se teď tak ukládají hodnoty do konfiguračního souboru a já nechci posunout význam v konfiguráku o 1, a proto, že mi přijde dobré držet konzistentní obsah souboru s tím, co se zobrazuje v GUI.

I jinde v hJOP se často používá číslování od 0, například u vstupů a výstupů RCS, takže by to pro učivatele mohlo být přijatelné.

Co myslíš @petrilakm?
