### ISSUE TITLE
Zvážit zrušení PN a NOT při přepnutí na dálkový provoz

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#229]

**Comment by horacekj** [comment]
ESA to tak má.

**Comment by petrilakm** [comment]
Já bych to tam dal. Přepnutím na DP zrušit všechny nouzové operace.

Navíc i nepřihlášený člověk může na návěstidle zvolit STUJ.

Stavy (obsazení úseku, závěry) se ukazují i nepřihlášenému. Teď je to celé fialové.

**Comment by horacekj** [comment]
Založil jsem issue #232, kde můžeme řešit, jaké volby povolit při oprávnění pro čtení.

**Comment by OndraHoust** [comment]
> Já bych to tam dal. Přepnutím na DP zrušit všechny nouzové operace.
> 
> Navíc i nepřihlášený člověk může na návěstidle zvolit STUJ.
> 
> Stavy (obsazení úseku, závěry) se ukazují i nepřihlášenému. Teď je to celé fialové.

Jo takhle... špatně jsem vyložil otázku. Pak ano, souhlasím.

**Comment by horacekj** [comment]
Asi i odznačit označené úseky pro NUZ, pokud nebylo spuštěno NUZ přes dopravní kancelář, ale pouze zůstaly označené úseky.
