### ISSUE TITLE
Povolit některé volby při oprávnění pro čtení

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#232]
Otázka je, které. ESA umožňuje dát `STUJ` na návěstidle a upravovat štítky a možná i něco dalšího.

Já bych byl asi pro žádné volby neumožnit, protože v modelu jsme v poněkud striktnější situaci, než na skutečné železnici. V modelu často běží panel s oprávněním pro čtení na náhodném počítači pro náhled veřejnosti a určitě nechci, aby veřejnost zadávala štítky nebo shazovala návěstidla.

Navrhuji umožnit zobrazení menu bez voleb (to nyní nejde), aby bylo možné zjistit vidět názvy bloků – to mi přijde jako užitečné při čtení. Něco dalšího?

**Comment by OndraHoust** [comment]
No v těch oprávněních, souvisejících výpisů stavů, chybových hlášek atd. je dost velký bordel. Třeba u mě bez oprávnění neuděláš vůbec nic. Zkrátka jak to kdo nakonfiguruje, tak to je... Skoro bych i řekl co stanice to originál 😄 

![2L](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/4dde8f74-abdd-45b4-88ba-d101b3e404ec)
![4ak](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/b34a9ef6-49fe-4a91-bf07-0a0c6ea3caaa)
![pzs](https://github.com/kmzbrnoI/hJOPserver/assets/55841765/146ce5fc-bc70-4784-a145-7423a9fd3b88)

**Comment by horacekj** [comment]
Teď mě napadá, že je možná rozdíl, když je obsluha bez oprávnění a když oprávnění má, ale stanici zrovna neřídí - je přepnutá na dálkový provoz.

**Comment by horacekj** [comment]
Logicky by mi dávalo smysl v menu povolit všechny volby, které umožní zjistit stav prvku.

Napadají mě tyto:
* STIT - ale jen pro zobrazení štítku, ne pro úpravu
* VYL - ale jen pro zobrazení výluky ne pro úpravu
* INFO vlak - zobrazení informací o vlaku
* V menu úseku zobrazovat čísla souprav (mj. kvůli INFO vlak).
* STAV - u AC, v budoucnu u přejezdů

**Comment by OndraHoust** [comment]
> Teď mě napadá, že je možná rozdíl, když je obsluha bez oprávnění a když oprávnění má, ale stanici zrovna neřídí - je přepnutá na dálkový provoz.

Je to možné, ale osobně si myslim, že se to prostě zrušilo. Ono co si budem povídat, bylo to naprosto k ničemu. Jen taková ta nutná železničářská byrokracie, protože stejně nikdo kdo nemá kartu PIK nemá přístup k pc/do budovy a kdo kartu má, má i oprávnění...

**Comment by OndraHoust** [comment]
> Logicky by mi dávalo smysl v menu povolit všechny volby, které umožní zjistit stav prvku.
> 
> Napadají mě tyto:
> 
> * STIT - ale jen pro zobrazení štítku, ne pro úpravu
> * VYL - ale jen pro zobrazení výluky ne pro úpravu
> * INFO vlak - zobrazení informací o vlaku
> * V menu úseku zobrazovat čísla souprav (mj. kvůli INFO vlak).
> * STAV - u AC, v budoucnu u přejezdů

jinak s tímhle by se dalo souhlasit
