### ISSUE TITLE
Doplnit zpoždění uvolnění závěrů úseků

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#240]
Umožnit:
* globální čas
* čas per úsek
* čas per úsek v jízdní cestě

Vybere se maximum.

**Comment by horacekj** [comment]
Je potřeba dořešit, co se závěrem posledního úseku - momentálně se natvrdo ruší se zrušením závěru předposledního úseku (až na jednoúsekové JC).

**Comment by OndraHoust** [comment]
Na tohle nejde odpovědět (stejně jak na bílou na přejezdech) Jde o to, jestli si HJOP představuješ jako zab. zař. nebo jen jako způsob řízení zab. zař. (tak jako JOP). Mezi námi to není ani jedno a zárověň tak trochu obojí... Pokud si to představuješ jako zab. zař., pak si sám zvol jak to bude. Protože jestli to má být jen jako JOP, pak záleží na tom, které zab zař má v tu chvíli HJOP představovat... Bylo by tam milion odlišností a bylo by to téměř nemožné nakonfigurovat, protože má stejně každá stanice odlišnosti byť jsou všechny se stejným zab. zař..
Pokud to má představovat třeba ETB tak tam se závěr zruší obsazením dalšího úseku (neplatí pokud je další úsek nehlídaný), volností vlastního úseku a uvolněním závěru předešlého úseku. Takže ve výsledku, když by vlak zastavil nekdě uprostřed VC, tak vše za ním už bude bez závěru. Jakékoliv fyzické zpoždění je dáno rychlostí relé (v našem pžípadě spíš pomalostí relé) Vše co jsem popsal se děje FYZICKY (releově), bohužel to co vidíš v JOP je ještě upravované vlastní konfigurací ASW, takže zrovna závěry mají určité manualně vložené zpoždění. (tuším, že to bude mít něco společného s maximální rychlostí ve stanici, ale ruku za to nedám)
AŽD71/DRS to bude mít zase jinak, ESA taky a pochopitelně taky každá její verze to bude mít jinak...

Taky se závěry chovají jinak s KO a jinak s PCN... třeba u PCN se čeká o hodně déle na uvolnění závěru právě u posledního závěru, který je před nehlídanou kolejí (typicky manipulační koleje, vjezdy do depa, ranžír atd.) Proč? Netuším.


Jak to vidím já: je to tvoje vlastní zab. zař. a ty si urči jak to chceš mít. Já osobně bych dal všude max 1s závěr pro jednoduchost.
