### ISSUE TITLE
Čas rušení jízdních cest

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPserver#250]
* Umožnit u jízdní cesty definovat seznam rozhodných úseků pro prodloužení času rušení JC.
  - Umožnost vázat na subúseky?
* Jakmile je byť jediný úsek jednou obsazen, čas rušení JC se prodloužuje na delší. Čas už se nikdy nezkrátí (i po uvolnění všech rozhodných úseků).

**Comment by OndraHoust** [comment]
Tady není moc o čem se bavit. Zrovna tohle norma určuje celkem jasně. 

9.4.3  
Po povelu ke zrušení závěru neprojeté vlakové cesty, ve které vlak neminul návěstidlo na začátku vlakové cesty, se smí závěr vlakové cesty zrušit: 
a)  ihned, jestliže se ještě nerozsvítila dovolující návěst pro stavěnou cestu; 
b)  po zhasnutí dovolující návěsti, jestliže: 
-  na tratích bez vlakového zabezpečovacího zařízení se vlak ještě nepřiblížil k místu předepsané viditelnosti návěstidla, které je předvěstí hlavního návěstidla na začátku vlakové cesty; 
-  na tratích s vlakovým zabezpečovacím zařízením vlak neminul místo, od kterého se poprvé mohla přenést na vozidlo informace o tom, že hlavní návěstidlo na začátku rušené vlakové cesty ukazuje dovolující návěst (zpravidla začátek kódovaného úseku před jeho „předvěstí“); 

c)  nejdříve za 3 minuty po zhasnutí dovolující návěsti na návěstidle na začátku cesty v ostatních případech


Jinými slovy: 

- Při rušení vjezdu: ihned pokud vlak nešlápl do úseku předvěsti (tzn nemá kód od předvěsti= dva volné oddíly před vjezdem) -v praxi je to ještě o oddíl dál, nikdo neví proč. Všechno ostatní 3minuty. 
- rušení odjezdu: ihned pokud vlak neprojel předvěstí (tzn nemá kód vjezdu= jeden volný oddíl před vjezdem). Všechno ostatní 3 minuty.

V obou případech samozřejmě platí, že když se ještě nerozsvítilo návěstidlo, tak se ruší ihned pochopitelně.

**Comment by OndraHoust** [comment]
9.4.4  Po povelu ke zrušení závěru neprojeté posunové cesty, ve které posunový díl neminul návěstidlo na začátku posunové cesty, se smí závěr posunové cesty zrušit: 
a)  ihned, jestliže se ještě nerozsvítila dovolující návěst pro stavěnou cestu; 
b)  po zhasnutí dovolující návěsti, jestliže lze technickými prostředky vyhodnotit, že kolej v délce alespoň 100 m před návěstidlem dovolujícím posun je volná; 
c)  nejdříve za 1 minutu po zhasnutí dovolující návěsti na návěstidle na začátku cesty v ostatních případech.

**Comment by horacekj** [comment]
Nakonec navázáno zatím pouze na úsek těsně před návěstidlem. Implementováno, že pokud dojde k jeho obsazení, ruší se cesta od té doby vždy dlouhým časem. Zjednodušenou implementaci oproti realitě jsem volil, protože vlak v modelu zastavuje mnohem rychleji a navíc pod kontrolu počítače zastavuje okamžitě po změně návěsti.

V budoucnu můžeme doladit detaily, pokud by o to někdo měl zájem.

Situace, kdy modelový brzdící vlak projede čerstvě shozenou návěst, teď v hJOP bude vyadat takto:
1. Vlak obsadí přibližovací úsek, odteď se ruší cesta dlouhým časem.
2. Výpravčí vydá povel `RC`, běží dlouhý čas.
3. Vlak obsadí první úsek cesty.
4. Dojde je zrušení odpočtu času a k možnosti `RC` na návěstidle. Závěr cesty zůstává.
5. Vlak zastaví.
6. Po zastavení vlaku výpravčí provede zrušní závěrů volbou `NUZ>` na úsecích.

Toto chování by mělo být do velké míry v souladu s chováním ESA a přijde mi bezpečně a rozumné.
